title: Idea Validation Bootcamp 
description: Idea Validation est un bootcamp intensif qui accompagne les participants dans la validation rapide et méthodique de leur idée de projet à travers des prototypes, des tests de marché et des retours utilisateurs.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
